dictionaries = ["en_us"]
words = [
  "addrx",
  "clzll",
  "coarray",
  "constness",
  "dataa",
  "discr",
  "dlbase",
  "ehdr",
  "ehsize",
  "endianity",
  "exprloc",
  "ileb",
  "keysym",
  "loclistx",
  "mb_iconerror",
  "mktmp",
  "phentsize",
  "phnum",
  "phoff",
  "rnglist",
  "rnglists",
  "rnglistsptr",
  "rnglistx",
  "shentsize",
  "shnum",
  "shoff",
  "shstrndx",
  "smeets",
  "syscalls",
  "tlib",
  "trunc",
  "fract",
]
